# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171215_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='IP地址')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
            ],
        ),
    ]
