# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_iport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='roles',
            field=models.ManyToManyField(to='app01.Role'),
        ),
    ]
