# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171215_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='iport',
            name='creat_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
