# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_iport_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iport',
            name='creat_time',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
    ]
