# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180102_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=64, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
