# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
    ]
