# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='caption',
            field=models.CharField(max_length=23, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app04.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='app04.Role', verbose_name='角色'),
        ),
    ]
